start: entry // Need entry+ for test.py

entry: ENTRY_TYPE LBRACE WORD COMMA fields RBRACE // Overall BibTeX Format

fields: field+

field: FIELD_NAME EQ value COMMA?

value: braced_value
 | QUOTED // Accounts for quoatation marks instead of braces
 | words

words: WORD+

LBRACE: "{"
RBRACE: "}"
COMMA.1: ","
EQ: "="

ENTRY_TYPE.5: /(@article|@book|@misc|@booklet|@inbook|@incollection|@inproceedings|@manual|@masterthesis|@phdthesis|@proceedings|@techreport|@unpublished)/i

FIELD_NAME.7: /(address|annote|author|booktitle|chapter|copyright|edition|editor|howpublished|institution|journal|keywords|month|note|number|organization|pages|publisher|school|series|title|type|volume|year|doi|issn|isbn|url)/i

QUOTED.7: /"[^"]*"/   // match entire "..." as one token

braced_value.1: LBRACE braced_content RBRACE

braced_content.1: (WORD | FIELD_NAME | EQ | QUOTED | COMMA | braced_value)*   // recursive, allowing nested braces

WORD.1: /[A-Za-z0-9_\-#\$%&*+\/;.!?~^:áéíóúñ()]+|\\[^\s]/ // Able to accept variety of characters (but NOT the comma)

WS: /[ \t\n\r]+/
%ignore WS
